### PR TITLE
Added aszdziennik.pl

### PR DESCRIPTION
**Pull request by maciekmm**
Aszdziennik is a polish site which goal is to write fake news/articles. They annotate every news with "To jest ASZdziennik. Wszelkie wydarzenia i cytaty zostały zmyślone." which translates to "It is ASZdziennik. All events and quotes are made up."

### CODE REVIEW

**Comment by hexonaut** [comment]
Is this an intentionally satirical website?

**Comment by maciekmm** [comment]
@Blank101 Yes. It is often based on the current political situation which might be misleading for some people.

**Comment by hexonaut** [comment]
I want to keep satire separate from fake news sites. Could you add it to a new array called "satire" instead of "fakenews"?

**Comment by hexonaut** [comment]
"This site is known for posting fake information." could that be changed to "This site is known for posting satire." ?

**Pull request merged**
